# Generated by Django 4.0.2 on 2022-03-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_well_number', models.BigIntegerField()),
                ('oil', models.IntegerField()),
                ('gas', models.IntegerField()),
                ('brine', models.IntegerField()),
            ],
        ),
    ]
