# Generated by Django 4.0.2 on 2022-03-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='id',
        ),
        migrations.AlterField(
            model_name='production',
            name='api_well_number',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
